/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.ipoki.android.plugin;

public final class R {
    public static final class array {
        public static final int languages=0x7f040000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int ipokito=0x7f020000;
    }
    public static final class id {
        public static final int button_cancel=0x7f060008;
        public static final int button_save=0x7f060007;
        public static final int comment_text_tv=0x7f060005;
        public static final int comment_user_tv=0x7f060004;
        public static final int edit_comment=0x7f060006;
        public static final int edit_password=0x7f06000a;
        public static final int edit_ping_server=0x7f06000b;
        public static final int edit_username=0x7f060009;
        public static final int latitude_tv=0x7f060003;
        public static final int longitude_tv=0x7f060002;
        public static final int spinner_lang=0x7f06000c;
        public static final int state_tv=0x7f060001;
        public static final int username_tv=0x7f060000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int message=0x7f030001;
        public static final int settings=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int button_cancel=0x7f050008;
        public static final int button_save=0x7f050007;
        public static final int connected=0x7f05000a;
        public static final int disconnected=0x7f05000b;
        public static final int enable_sound=0x7f050006;
        public static final int height=0x7f05000e;
        public static final int ipoki_url=0x7f050011;
        public static final int language=0x7f050005;
        public static final int latitude=0x7f05000c;
        public static final int longitude=0x7f05000d;
        public static final int message_received=0x7f050010;
        public static final int password=0x7f050003;
        public static final int ping_server=0x7f050004;
        public static final int preferences_file=0x7f050001;
        public static final int speed=0x7f05000f;
        public static final int user=0x7f050009;
        public static final int username=0x7f050002;
    }
}
